### ISSUE TITLE
RouterLink is too monotonous

### ISSUE THREAD

**Issue by Revent5** [easyroute-router/easyroute#10]
![image](https://user-images.githubusercontent.com/84359418/185591964-9c1a78cc-46ea-4a0c-83dc-14b0e8266730.png)
![image](https://user-images.githubusercontent.com/84359418/185592006-c35d4f8f-798b-417c-bd02-3962d8c50693.png)

**Comment by mav-inv-tech** [comment]
Do you mean _verbose_? If so, I agree, but there might be a good reason that it doesn't bind to <a>.

**Comment by lyohaplotinka** [comment]
I close, as the opinion is rather subjective. Plus, it's not very clear how you would like to see the component.
